name: Docker Publish

on:
 push:
   branches: [ master ]

 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v2

     - name: Docker Build
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blogproject .

     - name: Docker Push
       run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         docker push ${{ secrets.DOCKER_USERNAME }}/blogproject
